"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Loader2, Plus, X, Save } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface CourseFormData {
  title: string;
  description: string;
  category: string;
  tags: string[];
  price: number;
  modules: { title: string }[];
}

export default function AICourseCreator() {
  const [activeTab, setActiveTab] = useState<"ai" | "manual">("ai");
  const [aiTopic, setAiTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState<CourseFormData>({
    title: "",
    description: "",
    category: "",
    tags: [],
    price: 0,
    modules: [],
  });
  const [tagInput, setTagInput] = useState("");
  const { toast } = useToast();

  const generateWithAI = async () => {
    if (!aiTopic.trim()) {
      toast({
        title: "Error",
        description: "Please enter a course topic",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("/api/ai/generate-lesson", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: aiTopic,
          level: "intermediate",
          numQuestions: 5,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to generate course");
      }

      const aiData = data.data;

      // Auto-fill form with AI-generated data
      setFormData({
        title: aiData.lessonTitle || `Complete ${aiTopic} Course`,
        description:
          aiData.objective || `Learn everything about ${aiTopic} with practical examples and exercises.`,
        category: inferCategory(aiTopic),
        tags: aiData.keyPoints?.slice(0, 5) || [],
        price: 0,
        modules: [
          { title: `Introduction to ${aiTopic}` },
          { title: aiData.lessonTitle || `Core Concepts` },
          { title: `Practical Examples` },
        ],
      });

      toast({
        title: "Success!",
        description: "Course outline generated by AI. You can now edit and save.",
      });

      // Switch to manual tab to show generated content
      setActiveTab("manual");
    } catch (error: any) {
      console.error("AI generation error:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to generate course with AI",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const inferCategory = (topic: string): string => {
    const topicLower = topic.toLowerCase();
    if (
      topicLower.includes("web") ||
      topicLower.includes("html") ||
      topicLower.includes("css") ||
      topicLower.includes("react") ||
      topicLower.includes("vue")
    ) {
      return "web-development";
    } else if (
      topicLower.includes("python") ||
      topicLower.includes("java") ||
      topicLower.includes("programming") ||
      topicLower.includes("javascript")
    ) {
      return "programming";
    } else if (topicLower.includes("ai") || topicLower.includes("machine learning") || topicLower.includes("ml")) {
      return "artificial-intelligence";
    } else if (topicLower.includes("data") || topicLower.includes("analytics")) {
      return "data-science";
    }
    return "other";
  };

  const addTag = () => {
    if (tagInput.trim() && !formData.tags.includes(tagInput.trim())) {
      setFormData({ ...formData, tags: [...formData.tags, tagInput.trim()] });
      setTagInput("");
    }
  };

  const removeTag = (index: number) => {
    setFormData({ ...formData, tags: formData.tags.filter((_, i) => i !== index) });
  };

  const addModule = () => {
    setFormData({ ...formData, modules: [...formData.modules, { title: "" }] });
  };

  const updateModule = (index: number, title: string) => {
    const newModules = [...formData.modules];
    newModules[index] = { title };
    setFormData({ ...formData, modules: newModules });
  };

  const removeModule = (index: number) => {
    setFormData({ ...formData, modules: formData.modules.filter((_, i) => i !== index) });
  };

  const handleSave = async () => {
    if (!formData.title || !formData.description) {
      toast({
        title: "Error",
        description: "Please fill in title and description",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      const response = await fetch("/api/courses", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to create course");
      }

      toast({
        title: "Success!",
        description: "Course created successfully",
      });

      // Reset form
      setFormData({
        title: "",
        description: "",
        category: "",
        tags: [],
        price: 0,
        modules: [],
      });
      setAiTopic("");
      setActiveTab("ai");
    } catch (error: any) {
      console.error("Save error:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to create course",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-purple-600" />
          Create Course with AI
        </CardTitle>
        <CardDescription>Generate a complete course outline with AI or create manually</CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "ai" | "manual")}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="ai">
              <Sparkles className="h-4 w-4 mr-2" />
              AI Generate
            </TabsTrigger>
            <TabsTrigger value="manual">Manual Entry</TabsTrigger>
          </TabsList>

          {/* AI Generation Tab */}
          <TabsContent value="ai" className="space-y-4 mt-4">
            <div className="border rounded-lg p-6 space-y-4 bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-950 dark:to-blue-950">
              <div className="flex items-start gap-3">
                <Sparkles className="h-5 w-5 text-purple-600 mt-1 shrink-0" />
                <div className="flex-1 space-y-4">
                  <div>
                    <h3 className="font-semibold text-lg mb-2">Generate Course with AI</h3>
                    <p className="text-sm text-muted-foreground mb-4">
                      Enter a topic and let AI create a complete course outline. You can edit everything before
                      creating.
                    </p>
                  </div>

                  <div className="space-y-3">
                    <div>
                      <Label htmlFor="aiTopic">Course Topic</Label>
                      <Input
                        id="aiTopic"
                        placeholder="e.g., React Hooks, Python for Beginners, Web Design Fundamentals..."
                        value={aiTopic}
                        onChange={(e) => setAiTopic(e.target.value)}
                        onKeyPress={(e) => {
                          if (e.key === "Enter") {
                            e.preventDefault();
                            generateWithAI();
                          }
                        }}
                        className="text-base"
                      />
                    </div>

                    <Button
                      type="button"
                      onClick={generateWithAI}
                      disabled={loading || !aiTopic.trim()}
                      className="w-full"
                      size="lg"
                    >
                      {loading ? (
                        <>
                          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                          Generating with AI...
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-4 w-4 mr-2" />
                          Generate Course Outline
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className="text-sm text-muted-foreground text-center p-4 bg-muted/50 rounded">
              After generation, switch to <strong>Manual Entry</strong> tab to review and edit
            </div>
          </TabsContent>

          {/* Manual Entry Tab */}
          <TabsContent value="manual" className="space-y-6 mt-4">
            <div className="space-y-4">
              <div>
                <Label htmlFor="title">Course Title</Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="Enter course title"
                />
              </div>

              <div>
                <Label htmlFor="description">Description</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Enter course description"
                  rows={4}
                />
              </div>

              <div>
                <Label htmlFor="category">Category</Label>
                <Input
                  id="category"
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  placeholder="e.g., web-development, programming, data-science"
                />
              </div>

              <div>
                <Label>Tags</Label>
                <div className="flex gap-2 mb-2">
                  <Input
                    value={tagInput}
                    onChange={(e) => setTagInput(e.target.value)}
                    onKeyPress={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        addTag();
                      }
                    }}
                    placeholder="Add a tag and press Enter"
                  />
                  <Button type="button" onClick={addTag} variant="outline" size="icon">
                    <Plus className="h-4 w-4" />
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {formData.tags.map((tag, index) => (
                    <Badge key={index} variant="secondary" className="gap-1">
                      {tag}
                      <X className="h-3 w-3 cursor-pointer" onClick={() => removeTag(index)} />
                    </Badge>
                  ))}
                </div>
              </div>

              <div>
                <Label htmlFor="price">Price (VND)</Label>
                <Input
                  id="price"
                  type="number"
                  value={formData.price}
                  onChange={(e) => setFormData({ ...formData, price: Number(e.target.value) })}
                  placeholder="0 for free"
                />
              </div>

              <div>
                <div className="flex items-center justify-between mb-2">
                  <Label>Modules</Label>
                  <Button type="button" onClick={addModule} variant="outline" size="sm">
                    <Plus className="h-4 w-4 mr-1" />
                    Add Module
                  </Button>
                </div>
                <div className="space-y-2">
                  {formData.modules.map((module, index) => (
                    <div key={index} className="flex gap-2">
                      <Input
                        value={module.title}
                        onChange={(e) => updateModule(index, e.target.value)}
                        placeholder={`Module ${index + 1} title`}
                      />
                      <Button
                        type="button"
                        onClick={() => removeModule(index)}
                        variant="destructive"
                        size="icon"
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <Button onClick={handleSave} disabled={loading} className="w-full" size="lg">
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Creating Course...
                </>
              ) : (
                <>
                  <Save className="h-4 w-4 mr-2" />
                  Create Course
                </>
              )}
            </Button>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
