import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import connectDB from "@/lib/mongodb";
import Lesson from "@/models/Lesson";
import mongoose from "mongoose";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { 
      topic, 
      level, 
      numQuestions, 
      moduleId, 
      order,
      objectives,
      duration 
    } = body;

    // Validate required fields
    if (!topic) {
      return NextResponse.json(
        { error: "Topic is required" },
        { status: 400 }
      );
    }

    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json(
        { error: "OpenAI API key not configured" },
        { status: 500 }
      );
    }

    // Initialize OpenAI
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const prompt = `You are an expert educational content creator and course designer.
Your task is to create a complete lesson with detailed content and quiz questions in Vietnamese.

# Lesson Information:
- Topic: ${topic}
- Level: ${level || "intermediate"}
- Number of quiz questions: ${numQuestions || 5}
- Objectives: ${objectives || "Students understand the topic and can apply it in practice"}
- Expected duration: ${duration || 30} minutes

# Requirements:
1. Create detailed, easy-to-understand lesson content with clear structure
2. Include sections: Introduction, Main Content (divided into subsections), Summary
3. Create ${numQuestions || 5} multiple choice questions with 4 answers each
4. Each question needs detailed explanation for correct answer
5. Questions should vary in difficulty (easy, medium, hard)
6. All content must be in Vietnamese language

# Format JSON trả về:
{
  "lessonTitle": "Tiêu đề bài học hấp dẫn",
  "objective": "Mục tiêu học tập cụ thể",
  "content": "Nội dung bài học đầy đủ với markdown format, bao gồm:\\n\\n## Giới thiệu\\n...\\n\\n## Nội dung chính\\n### Phần 1\\n...\\n### Phần 2\\n...\\n\\n## Tóm tắt\\n...",
  "duration": ${duration || 30},
  "keyPoints": [
    "Điểm quan trọng 1",
    "Điểm quan trọng 2",
    "Điểm quan trọng 3"
  ],
  "quiz": [
    {
      "question": "Câu hỏi 1?",
      "options": ["Đáp án A", "Đáp án B", "Đáp án C", "Đáp án D"],
      "correctAnswer": 0,
      "explanation": "Giải thích chi tiết tại sao đáp án này đúng và các đáp án khác sai",
      "difficulty": "easy"
    }
  ],
  "resources": [
    {
      "title": "Tài liệu tham khảo 1",
      "url": "https://example.com",
      "type": "article"
    }
  ],
  "practiceExercises": [
    "Bài tập thực hành 1",
    "Bài tập thực hành 2"
  ]
}

Only return valid JSON, no additional explanatory text.`;

    // Call OpenAI API
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: "You are an expert educational content creator. Always respond with valid JSON only, no additional text."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      response_format: { type: "json_object" }
    });

    const resultText = completion.choices[0]?.message?.content || "{}";
    
    // Parse JSON from response
    let aiGenerated;
    try {
      // Extract JSON from response
      const jsonMatch = resultText.match(/\{[\s\S]*\}/);
      const jsonText = jsonMatch ? jsonMatch[0] : resultText;
      aiGenerated = JSON.parse(jsonText);
    } catch (parseError) {
      console.error("Error parsing AI response:", parseError);
      console.error("Raw response:", resultText);
      return NextResponse.json(
        { error: "Invalid response from AI", details: resultText },
        { status: 500 }
      );
    }

    // If moduleId provided, automatically save lesson to database
    if (moduleId) {
      await connectDB();
      
      const newLesson = await Lesson.create({
        title: aiGenerated.lessonTitle,
        content: aiGenerated.content,
        module: new mongoose.Types.ObjectId(moduleId),
        order: order || 1,
        duration: aiGenerated.duration || duration || 30,
        type: "video", // Default type
        videoUrl: "", // Teacher will upload later
        isPublished: false, // Not published yet
        resources: aiGenerated.resources || [],
      });

      return NextResponse.json({
        success: true,
        lesson: newLesson,
        aiGenerated: aiGenerated,
        message: "Lesson created and saved to database"
      });
    }

    // If no moduleId, just return AI generated data
    return NextResponse.json({
      success: true,
      data: aiGenerated,
      message: "Lesson content generated by AI"
    });

  } catch (error: any) {
    console.error("AI Generate Lesson Error:", error);
    return NextResponse.json(
      { 
        error: "Failed to generate lesson", 
        details: error.message 
      },
      { status: 500 }
    );
  }
}

// GET endpoint for testing
export async function GET() {
  return NextResponse.json({
    message: "AI Lesson Generator API (OpenAI GPT-4o-mini)",
    usage: "POST with { topic, level, numQuestions, moduleId?, order?, objectives?, duration? }",
    example: {
      topic: "Introduction to JavaScript",
      level: "beginner",
      numQuestions: 5,
      objectives: "Understand JavaScript basics and usage",
      duration: 45
    }
  });
}
